name: TitanBoxRFP
main: com.firesoftitan.play.titanbox.rfp.TitanBoxRFP
version: @plugin_version@
author: [freethemice, Tristiisch]
softdepend: [Vault]
api-version: 1.13
commands:
  TRFP:
    description: ReallyFakePlayerCommands
    usage: /<command>
  RFP:
    description: ReallyFakePlayerCommands
    usage: /<command>